app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::resource('leads', 'LeadsController', ['only' => ['store']]);
    Route::get('/', ['uses' => 'LeadsController@index', 'as' => 'root']);
});

app/AppModel.php
<?php

namespace App;

// use Validator;
use Illuminate\Support\Facades\Validator;
use Illuminate\Database\Eloquent\Model;

class AppModel extends Model
{
    protected static $rules = array();

    protected $errors;

    public function isValid()
    {
        // make a new validator object
        $v = Validator::make($this->getAttributes(), AppModel::$rules);

        // check for failure
        if ($v->fails())
        {
            // set errors and return false
            $this->errors = $v->errors();
            return false;
        }

        // validation pass
        return true;
    }

    public function errors()
    {
        return $this->errors;
    }

    public static function rules() {
        $class = get_called_class();
        return $class::$rules;
    }
}

app/Lead.php
<?php

namespace App;

use App\AppModel;
use Carbon\Carbon;
use Illuminate\Container\Container;
use Log;

class Lead extends AppModel
{

  protected static function boot() {
      parent::boot();

      static::creating(function($lead) {
        if (!$lead->isValid()) return false;

        $lead->calculateScore();
        return true;
      });

      static::created(function($lead) {
        // $lead->sendToApi();
        return true;
      });

  }

  protected static $rules = [
    'name' => ['required', 'regex:/^((\b\p{L}{2,255}\b)\s*){2,}$/'],
    'email' => ['required', 'email'],
    'phone' => ['required'],
    'born_at' => ['required', 'date_format:d/m/Y'],
    'unit_id' => ['required']
  ];

  /**
   * Default values for attributes
   * @var  array an array with attribute as key and default as value
   */
  protected $attributes = [
    'score' => 10
  ];

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = ['name', 'email', 'born_at', 'phone', 'unit_id'];

  public function setBornAtAttribute($value)
  {
      $this->attributes['born_at'] = Carbon::createFromFormat('d/m/Y', $value);
  }

  public function ageScoreModifier() {
    $dateForAgeCalc = Carbon::createFromDate(2016, 6, 1);
    $interval = $this->born_at->diffInYears($dateForAgeCalc);
    switch (true) {
      case ($interval >= 18 && $interval < 40):
        return 0;
        break;
      case ($interval >= 40 && $interval < 100):
        return -3;
        break;
      default:
        return -5;
        break;
    }
  }

  protected function calculateScore() {
    Log::info($this->unit->unitScoreModifier());
    Log::info($this->ageScoreModifier());
    $this->score = $this->score + $this->unit->unitScoreModifier() + $this->ageScoreModifier();
  }

  public function unit()
  {
      return $this->belongsTo('App\Unit');
  }

  protected function sendToApi() {
    $client = Container::getInstance()->offsetGet('guzzle');
    $ret = $client->post('http://api.actualsales.com.br/join-asbr/ti/lead', [
      'form_params' => [
        'nome'            => $this->name,
        'email'           => $this->email,
        'telefone'        => $this->phone,
        'regiao'          => $this->unit->region->name,         #(Elemento do conjunto ["Norte", "Nordeste", "Sul", "Sudeste", "Centro-Oeste"])
        'unidade'         => $this->unit->name,                 #(Elemento do conjunto ["Porto Alegre", "Curitiba", "São Paulo", "Rio de Janeiro", "Belo Horizonte", "Brasília", "Salvador", "Recife", "INDISPONÍVEL"])
        'data_nascimento' => $this->born_at->format('Y-m-d'),   #(data no formato YYYY-mm-dd)
        'score'           => $this->score,                      #(int de 0 a 10)
        'token'           => 'a85846a2a6506569a80030f2cad0f282' # (String)
      ]
    ]);
    Log::info(var_export($ret, true));
  }
}

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{

  public function units()
  {
      return $this->hasMany('App\Unit');
  }

}

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['score_modifier', 'region_id', 'created_at', 'updated_at'];

    public function leads()
    {
        return $this->hasMany('App\Lead');
    }

    public function region()
    {
        return $this->belongsTo('App\Region');
    }

    public function unitScoreModifier() {
      return $this->region->score_modifier + $this->score_modifier;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LeadsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Region;
use App\Lead;

class LeadsController extends Controller
{

  /**
   * Responds to requests to GET /users
   */
  public function index()
  {
    $regions = Region::with('units')->get();
    return view('leads.index')->with('regions', $regions);
  }

  /**
   * Store a new lead.
   *
   * @param  Request  $request
   * @return Response
   */
  public function store(Request $request)
  {
    $messages = [
      'regex' => 'É necessário digitar o nome completo.',
      'email' => 'O email está incorreto',
      'required' => 'É de preenchimento obrigatório',
      'date_format' => 'Data inválida'
    ];
    $this->validate($request, Lead::rules(), $messages);
    $leadParams = $request->all();
    $lead = new Lead($leadParams);
    if ($lead->save()) {
        return response()->json(['status' => 'success']);
    } else {
        $regions = Region::with('units')->get();
        return view('products.create')->with('lead', $lead)->with('regions', $regions);
    }


    //
  }
}

resources/views/includes/head.blade.php
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>Compre Já</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

resources/views/layouts/default.blade.php
<!doctype html>
<html>
  <head>
      @include('includes.head')
  </head>
  <body>
    <div class="container">

      <div class="row" style="margin:30px 0">
        <div class="col-lg-3">
          <img src="img/logo.png" class="img-thumbnail">
        </div>
        <div class="col-lg-9">
          <h3>Nome do Produto</h3>
        </div>
      </div>

      @yield('content')

    </div>
  </body>
</html>

resources/views/leads/index.blade.php
@extends('layouts.default')
@section('content')
  {!! BootForm::open()->action( route('leads.store') ); !!}
    <div class="row">
      <div class="col-lg-6" id="form-container">
        <div id="step_1" class="form-step">
          <div class="panel panel-info">
            <div class="panel-heading">
              <div class="panel-title">
                Preencha seus dados para receber contato
              </div>
            </div>
            <div class="panel-body">
              <fieldset>
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Nome Completo</label>
                      <input class="form-control" type="text" name="name">
                      <span class="help-block"></span>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Data de Nascimento</label>
                      <input class="form-control" type="text" name="born_at" data-mask="00/00/0000">
                      <span class="help-block"></span>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Email</label>
                      <input class="form-control" type="text" name="email">
                      <span class="help-block"></span>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Telefone</label>
                      <input class="form-control" type="text" name="phone">
                      <span class="help-block"></span>
                    </div>
                  </div>
                </div>

                <div>
                  <a class="btn btn-lg btn-info next-step">Próximo Passo</a>
                </div>
              </fieldset>
            </div>
          </div>
        </div>

        <div id="step_2" class="form-step" style="display:none">
          <div class="panel panel-info">
            <div class="panel-heading">
              <div class="panel-title">
                Preencha seus dados para receber contato
              </div>
            </div>
            <div class="panel-body">
              <fieldset>
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Região</label>
                      <select class="form-control" id="region">
                        <option value="">Selecione a sua região</option>
                        @foreach ($regions as $region)
                          <option value="{{$region->id}}" data-units="{{$region->units->toJson()}}">{{$region->name}}</option>
                        @endforeach
                      </select>
                      <span class="help-block"></span>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="control-label">Unidade</label>
                      <select class="form-control" name="unit_id" id="units">
                        <option value="">Selecione a unidade mais próxima</option>
                      </select>
                      <span class="help-block"></span>
                    </div>
                  </div>
                </div>

                <div>
                  <button type="submit" class="btn btn-lg btn-info next-step">Enviar</button>
                </div>
              </fieldset>
            </div>
          </div>
        </div>

        <div id="step_sucesso" class="form-step" style="display:none">
          <div class="panel panel-info">
            <div class="panel-heading">
              <div class="panel-title">
                Obrigado pelo cadastro!
              </div>
            </div>
            <div class="panel-body">
                Em breve você receberá uma ligação com mais informações!
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <h1>Chamada interessante para o produto</h1>
        <h2>Mais uma informação relevante</h2>
      </div>
    </div>
  {!! BootForm::close() !!}
  <script>
    $(function () {
      $.applyDataMask();

      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });

      function fillErrorInFields(response) {
        $('.form-group').removeClass('has-error');
        $('.help-block').empty();
        for (fieldName in response) {
          $field = $('[name='+fieldName+']');
          $field.parents('.form-group').addClass('has-error');
          $field.siblings('.help-block').text(response[fieldName].join(', '));
        }
      }

      $('.next-step').click(function (event) {
        $this = $(this);
        $ret = $.post($('form').attr('action'), $('form').serialize());


        if ($(this).parents('.form-step').attr('id') === 'step_1') {
          $ret.fail(function (xhr){
            response = xhr.responseJSON;
            if (Object.keys(response).length > 1 ||
                Object.keys(response).indexOf('unit_id') < 0) {
              fillErrorInFields(response);
            } else {
              $this.parents('.form-step').hide().next().show();
            }
          });
        } else {
          $ret.fail(function (xhr){
            response = xhr.responseJSON;
            if (Object.keys(response).length === 1 &&
                Object.keys(response).indexOf('unit_id') >= 0) {
              fillErrorInFields(response);
            }
          }).done(function (){
            $this.parents('.form-step').hide().next().show();
          });
        }
        event.preventDefault();
      });

      $('#region').on('change', function(event) {
        var units = $('option:selected', this).data('units');
        $default = $('<option value="">Selecione a unidade mais próxima</option>');
        $('#units').empty().append($default);
        if (units) {
          for (unit of units) {
            $('#units').append('<option value="'+unit.id+'">'+unit.name+'</option>');
          }
        }
      });

      var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
          }
      };

      $('[name=phone]').mask(SPMaskBehavior, spOptions);
    });
  </script>
@stop